# Generated by Django 5.0.4 on 2024-05-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_username_login_usernam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='usernam',
            new_name='username',
        ),
    ]
