# Generated by Django 5.0.4 on 2024-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_compte_compte_cree'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_cree',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte_cree',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte_cree',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte_cree',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
