# Generated by Django 5.0.4 on 2024-05-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
        ('pages', '0006_compte_cree_email_compte_cree_nom_compte_cree_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_cree',
            name='reservation',
            field=models.ManyToManyField(null=True, to='formation.formation'),
        ),
    ]
