# Generated by Django 5.0.4 on 2024-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
        ('pages', '0007_compte_cree_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_cree',
            name='reservation',
            field=models.ManyToManyField(blank=True, null=True, to='formation.formation'),
        ),
    ]
