# Generated by Django 5.0.4 on 2024-05-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
        ('pages', '0008_alter_compte_cree_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte_cree',
            name='reservation',
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compte_cree')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
    ]
