# Generated by Django 5.0.4 on 2024-05-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_compte_cree_reservation_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
