# Generated by Django 5.0.4 on 2024-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
        ('pages', '0010_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_cree',
            name='formations_achetees',
            field=models.ManyToManyField(related_name='clients', to='formation.formation'),
        ),
    ]
