# Generated by Django 5.0.4 on 2024-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_compte_cree_formations_achetees'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
