# Generated by Django 5.0.4 on 2024-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
