# Generated by Django 5.0.4 on 2024-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
        ('pages', '0014_alter_reservation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='formations_res',
            field=models.ManyToManyField(related_name='reservatons', to='formation.formation'),
        ),
    ]
