# Generated by Django 5.0.4 on 2024-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_reservation_formations_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='formations_res',
            new_name='formations_reservees',
        ),
    ]
