# Generated by Django 5.0.4 on 2024-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_formations_achetees_compte_cree_formations_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_client',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_formations',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom_client',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
    ]
