# Generated by Django 5.0.4 on 2024-06-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_reservation_email_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='username_client',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
    ]
