# Generated by Django 5.0.4 on 2024-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
