# Generated by Django 5.0.4 on 2024-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_formation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.CharField(blank=True, choices=[('informatique', 'informatique'), ('industrielle', 'industrielle'), ('automatisme', 'automatisme')], max_length=50, null=True),
        ),
    ]
