# Generated by Django 5.0.4 on 2024-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_formation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='nombre',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
