# Generated by Django 5.0.4 on 2024-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_formation_nombre_alter_formation_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='nombre',
        ),
        migrations.AddField(
            model_name='formation',
            name='datetimes',
            field=models.DateTimeField(null=True),
        ),
    ]
