# Generated by Django 5.0.4 on 2024-06-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_datetimes_formation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/%d'),
        ),
    ]
